added apply, made ARM vars global, made repo vars inline

diff --git a/.github/workflows/tf-pipeline-paas.yml b/.github/workflows/tf-pipeline-paas.yml
--- a/.github/workflows/tf-pipeline-paas.yml
+++ b/.github/workflows/tf-pipeline-paas.yml
@@ -34,6 +34,10 @@ on:
 #These environment variables are used by the terraform azure provider to setup OIDD authenticate.
 env:
   TF_DIR: "./infra/paas/terraform"
+  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
 jobs:
   terraform-plan:
@@ -94,52 +98,88 @@ jobs:
       # https://nedinthecloud.com/2021/12/08/github-actions-with-terraform/
       - name: Terraform Init
         id: tf-init
-        env:
-          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-          RESOURCE_GROUP: ${{ vars.TF_RESOURCE_GROUP }}
-          STORAGE_ACCOUNT: ${{ vars.TF_STORAGE_ACCOUNT }}
-          CONTAINER_NAME: ${{ vars.TF_CONTAINER_NAME }}
-          KEY: "${{ env.lowerCaseEnvValue }}/terraform.tfstate"
+        # env:
+          # ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+          # ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+          # ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+          # ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+          # RESOURCE_GROUP: ${{ vars.TF_RESOURCE_GROUP }}
+          # STORAGE_ACCOUNT: ${{ vars.TF_STORAGE_ACCOUNT }}
+          # CONTAINER_NAME: ${{ vars.TF_CONTAINER_NAME }}
+          # KEY: "${{ env.lowerCaseEnvValue }}/terraform.tfstate"
         run: |
           cd $TF_DIR
-          terraform init -reconfigure -backend-config="key=$KEY" -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"
+          terraform init -reconfigure -backend-config="${{ env.lowerCaseEnvValue }}/terraform.tfstate" -backend-config="storage_account_name=${{ vars.TF_STORAGE_ACCOUNT }}" -backend-config="container_name=${{ vars.TF_CONTAINER_NAME }}" -backend-config="resource_group_name=${{ vars.TF_RESOURCE_GROUP }}"
       #     # Checks that all Terraform configuration files adhere to a canonical format
       #     # Will fail the build if not
       #     - name: Terraform Format
       #       run: terraform fmt -check
-
       # Generates an execution plan for Terraform
       # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
       - name: Terraform Plan
         id: tf-plan
-        env:
-          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
-          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
-          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
-          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+        # env:
+        #   ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+        #   ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+        #   ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+        #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         run: |
           cd $TF_DIR
-          export exitcode=0
           terraform plan -var-file ${{ env.lowerCaseEnvValue }}.tfvars -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
-#         echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
+        # echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
 
-#         if [ $exitcode -eq 1 ]; then
-#           echo Terraform Plan Failed!
-#           exit 1
-#         else
-#           exit 0
-#         fi
+        # if [ $exitcode -eq 1 ]; then
+        #   echo Terraform Plan Failed
+        #   exit 1
+        # else
+        #   exit 0
+        # fi
 
-#     # Save plan to artifacts
-#     - name: Publish Terraform Plan
-#       uses: actions/upload-artifact@v3
-#       with:
-#         name: tfplan
-#         path: tfplan
+      - name: Terraform Apply
+        # env:
+        #   ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
+        #   ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
+        #   ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
+        #   ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+        run: |
+          cd $TF_DIR
+          terraform apply -auto-approve tfplan
+# name: "Terraform Apply"
+#   # if: github.ref == 'refs/heads/main' && needs.terraform-plan.outputs.tfplanExitCode == 2
+#   runs-on: ubuntu-latest
+#   environment: production
+#   needs: [terraform-plan]
+
+#   steps:
+#     # Checkout the repository to the GitHub Actions runner
+#     - name: Checkout
+#       uses: actions/checkout@v3
+
+#     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
+#     - name: Setup Terraform
+#       uses: hashicorp/setup-terraform@v2
+
+#     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
+#     - name: Terraform Init
+#       run: terraform init
+
+# Download saved plan from artifacts
+# - name: Download Terraform Plan
+#   uses: actions/download-artifact@v3
+#   with:
+#     name: tfplan
+
+# # Terraform Apply
+# - name: Terraform Apply
+#   run: terraform apply -auto-approve tfplan
+
+# # Save plan to artifacts
+# - name: Publish Terraform Plan
+#   uses: actions/upload-artifact@v3
+#   with:
+#     name: tfplan
+#     path: tfplan
 
 #     # Create string output of Terraform Plan
 #     - name: Create String Output
