fixing init

diff --git a/.github/workflows/tf-pipeline-paas.yml b/.github/workflows/tf-pipeline-paas.yml
--- a/.github/workflows/tf-pipeline-paas.yml
+++ b/.github/workflows/tf-pipeline-paas.yml
@@ -62,23 +62,24 @@ jobs:
       # tf_actions_working_dir: "./infra/paas/terraform"
       # tf_actions_comment: true
 
-      # - name: Terraform Init
-      #   run: |
-      #     cd $TF_DIR
-      #     terraform init
+      - name: Terraform Init
+        id: tf-init
+        run: |
+          cd $TF_DIR
+          terraform init
 
-  #     # Checks that all Terraform configuration files adhere to a canonical format
-  #     # Will fail the build if not
-  #     - name: Terraform Format
-  #       run: terraform fmt -check
+      #     # Checks that all Terraform configuration files adhere to a canonical format
+      #     # Will fail the build if not
+      #     - name: Terraform Format
+      #       run: terraform fmt -check
 
-  #     # Generates an execution plan for Terraform
-  #     # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
-  #     - name: Terraform Plan
-  #       id: tf-plan
-  #       run: |
-  #         export exitcode=0
-  #         terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
+      # Generates an execution plan for Terraform
+      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
+      - name: Terraform Plan
+        id: tf-plan
+        run: |
+          export exitcode=0
+          terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?
 
   #         echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
 
